.TH "repr" "1"
.SH "NAME"
repr \(em escape unprintable characters\)
.SH "SYNOPSIS"
.PP
\fBrepr\fR [FILE]
.SH "DESCRIPTION"
.PP
The basic concept for this utility is to emulate python's repr() function

.SH "USAGE"
.IP "With a file specified" 10
\fBrepr\fR data.bin

.IP "As a filter" 10
 ... | \fBrepr\fR | ...

.SH "OPTIONS"
.PP
n/a

.SH "REQUIRES"
.PP
n/a

.SH "VERSION"
.PP
0.1337

.SH "BUGS"
.PP
n/a

.SH "SEE ALSO"
.PP
n/a

.SH "AUTHORS"
.PP
Zephyr zephyr@dirtbags.net
.PP
pi-rho pi-rho@tyr.cx
.PP
This man-page was written by pi-rho ubuntu@tyr.cx
