.TH "unhex" "1"
.SH "NAME"
unhex \(em translate hexits to their binary equivalent\)
.SH "SYNOPSIS"
.PP
\fBunhex\fR [FILE]
.SH "DESCRIPTION"
.PP
The basic concept for this utility is to translate hexits (00-ff) to their binary
equivalent.

.SH "USAGE"
.IP "With a file specified" 10
\fBunhex\fR data.bin

.IP "As a filter" 10
 ... | \fBunhex\fR | ...

.SH "OPTIONS"
.PP
n/a

.SH "REQUIRES"
.PP
n/a

.SH "VERSION"
.PP
0.1337

.SH "BUGS"
.PP
n/a

.SH "SEE ALSO"
.PP
n/a

.SH "AUTHORS"
.PP
Zephyr zephyr@dirtbags.net
.PP
pi-rho pi-rho@tyr.cx
.PP
This man-page was written by pi-rho ubuntu@tyr.cx
