.TH "xor" "1"
.SH "NAME"
xor \(em apply mask bytes to a stream using XOR
.SH "SYNOPSIS"
.PP
\fBxor\fR [\-x] <MASK>*
.SH "DESCRIPTION"
.PP
The basic concept for this utility is to apply a set of mask bytes, repeatedly,
to a stream of input. The application of the mask bytes is accomplished using
the bitwise XOR operation.

.SH "USAGE"
.IP "As a filter" 10
 ... | \fBxor\fR \-x 20 2f | ...

.SH "OPTIONS"
.PP
A summary of the options supported by \fBxor\fR is included below.

.IP "\-x" 10
The optional \fI\-x\fP flag tells xor that mask bytes are specified in
hexadecimal notation

.IP "MASK" 10
This represents a list of mask bytes to apply to the input stream. Bytes should
be listed in decimal, unless the optional \fI\-x\fR flag is
given.

.SH "REQUIRES"
.PP
n/a

.SH "VERSION"
.PP
0.1337

.SH "BUGS"
.PP
n/a

.SH "SEE ALSO"
.PP
n/a

.SH "AUTHORS"
.PP
Zephyr zephyr@dirtbags.net
.PP
This man-page was written by pi-rho ubuntu@tyr.cx
