.\" This manual is Copyright 2012 by pi-rho <ubuntu@tyr.cx>
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This package is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program. If not, see <http://www.gnu.org/licenses/>.
.\"
.\" On Debian systems, the complete text of the GNU General
.\" Public License version 3 can be found in "/usr/share/common-licenses/GPL-3".
.
.Dd May 23, 2012
.Dt HDNG 1
.Os "Network Reverse Engineering Toolkit" 1.1337
.
.Sh NAME
.Nm hdng
.Nd a hex dumper for the next generation
.
.Sh SYNOPSIS
.Nm hdng
.Op Fl h | Fl v
.Nm hdng
.Op Fl o x s g w Ar width
.Op Ar file
.Nm hdng
.Op Fl X | Fl G
.Op Ar file
.
.Sh DESCRIPTION
The basic concept for this utility is to emulate the base functionality of a hex
dumper as found in bsdmainutil's
.Xr hexdump 1
while providing better representation of the data. A special character set is
used so that one might better observe patterns in the data. Additionally,
the three areas of the hexdump (offsets, hexits, glyphs) can be turned off
and the width of data represented in each line of data can be changed.
.Pp
The available options include:
.Pp
.Bl -tag -compact -width Ds
.It Fl h
usage information
.It Fl v
the program's version
.It Fl o
do not display offsets, including the total byte count
.It Fl x
do not display hexits
.It Fl s
do not abbreviate redundant data
.It Fl g
do not display glyphs
.It Fl w Ar width
the
.Em width
of data to represent on each line of output
.El
.
.Ss Special Modes
The following flags are mutually exclusive. When specified,
.Nm
ignores all other flags.
.Pp
.Bl -tag -compact -width Ds
.It Fl X
turns on continuous
.Em hexdump
mode
.It Fl G
turns on continuous
.Em glyphdump
mode
.El
.
.Sh EXAMPLES
With a file specified
.D1 Ic $ Nm hdng Pa data.bin
.Pp
As a filter
.D1 Ic $ No ... | Nm hdng | No ...
.
.Sh SEE ALSO
.Xr hexdump 1 ,
.Xr repr 1 ,
.Xr unhex 1 ,
.Xr xor 1
.
.Sh AUTHORS
.An Zephyr Aq Ad zephyr@dirtbags.net ,
.An pi-rho Aq Ad pi-rho@tyr.cx
.
.Sh BUGS
Bugs may be submitted at
.Aq Ad https://bugs.launchpad.net/netre-tools
