name: Build/Test

on: 
  push:
    branches:
      - main

jobs:
  test:
    name: Test mothd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Test
        run: ./test.sh
