name: Build/Test

on: 
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  test:
    name: Test mothd
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve code
        uses: actions/checkout@v2

      - name: Build
        run: make

      - name: Test
        run: ./test.sh
