name: Build/Test

on: 
  push:
    branches:
      - master:
      - main
  pull_request:
    branches: 
      - master
      - main

jobs:
  test:
    name: Test mothd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make
      - name: Test
        run: ./test.sh
