name: Build/Test

on: 
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    name: Build+test mothd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build+test
        run: make test
